USE [master]
GO

/****** Object:  Database [LoginDemo]    Script Date: 07/28/17 5:32:21 PM ******/
CREATE DATABASE [LoginDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoginDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQL2014\MSSQL\DATA\LoginDemo.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LoginDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQL2014\MSSQL\DATA\LoginDemo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LoginDemo] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoginDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoginDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoginDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoginDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoginDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoginDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoginDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LoginDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoginDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoginDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoginDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoginDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoginDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoginDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoginDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoginDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LoginDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoginDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoginDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoginDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoginDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoginDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LoginDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoginDemo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LoginDemo] SET  MULTI_USER 
GO

ALTER DATABASE [LoginDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoginDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LoginDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LoginDemo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LoginDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LoginDemo] SET  READ_WRITE 
GO


